steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - ViewAllEmployee
      - --runtime=go121
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=ViewAllEmployees
      - --region=europe-west1
      - --project=takeoff-task-3
